### PR TITLE
M3o client gen

### PR DESCRIPTION
**Pull request by lambdaR**
have a look @asim ... i will convert this PR to draft for now 

- The new github workflow (i called it _scheduler.yml_) has the ability to run all m3o generators at once or can run a specific one.

- the new generator is now called `m3o-client-gen`.

- I added new folder _cmd/release-note_  which contains a program to fetch the latest commit metadata (sha, html_url and message) from micro/services repo and use it to update CHANGELOG.md file in the m3o/m3o-dart repo.

### CODE REVIEW

**Comment by asim** [comment]
Sounds good. You will probably want to operate on the micro services dispatch event as well. Unless you see the triggers working differently.

**Comment by lambdaR** [comment]
that will be another PR to micro/services… and since you mentioned it, instead of triggering the scheduler.yml every time we push to micro/services we can write a new action that gets triggered on release. What do you think? or should we leave it. 

As for those individuals jobs in the scheduler.yml like generate-go you can add some buttons in your background dashboard (if exist) to trigger them as needed like in a situation where all clients have been successfully built and published except for go.

**Comment by asim** [comment]
Well I think we'd need to look at, if something is changing in micro/services, that implies its going to be deployed. So the clients would have to change accordingly as well. Whether its endpoint changes, fields, new services, etc.

On that point, maybe the scheduler should also trigger running/updating services?

**Comment by lambdaR** [comment]
I think the simplest way to achieve this is to make sure that we integrate a special tag in each commit like for example "add missing attributes in weather service [WEATHER-U]" and then in the scheduler jobs.generate we add new step that runs a similar program to the release-note that reads the tag [WEATHER-U] and then calls a special micro service passing it the tag to proceed with the update/run process in your backend.
[WEATHER-U] = micro update weather
[WEATHER-R] = micro run github.com/micro/services/weather

**Comment by asim** [comment]
Too complicated. We've done this before. Basically you get the git sha in the action and diff it for file changes. Any new folder is a new service. Any folder changes is an update.

**Comment by lambdaR** [comment]
>  We've done this before.

cool

> Basically you get the git sha in the action and diff it for file changes. Any new folder is a new service. Any folder changes is an update

In the scheduler.jobs.generate, how can we trigger that mechanism you mentioned above? should we add it

**Comment by asim** [comment]
We have a micro admin token `MICRO_ADMIN_TOKEN` available to GitHub actions. We can use this via the API or CLI to invoke the right call to the runtime. E.g /runtime/create and /runtime/update

**Comment by asim** [comment]
The alternative is to send an event to a specific service which we can then handle the actual deploy in the background

**Comment by lambdaR** [comment]
revert is your friend :)

**Pull request merged**
