### PR TITLE
Restructuring client-gen

### PR DESCRIPTION
**Pull request by lambdaR**
In order to create the Dart generator freely without adding complexities to the codebase , I have restructured the client-gen in a way that i think it will make it easy for each generator to be modified separately.

Dart generator is not complete yet, update will follow.

### CODE REVIEW

**Comment by asim** [comment]
I think there's a minor conflict in the code. Otherwise I'd look forward to welcoming a restructure.

**Comment by lambdaR** [comment]
Question, is there any reason why the execute permission of the generated files (clients) has 744 (rwxr--r–)?

Normally, files have 664 (rw-rw-r–) and folders have 775 (rwxrwxr-x).
Will follow the latter for now.

**Comment by asim** [comment]
> Question, is there any reason why the execute permission of the generated files (clients) has 744 (rwxr--r–)?
> 
> Normally, files have 664 (rw-rw-r–) and folders have 775 (rwxrwxr-x). Will follow the latter for now.

We did not do it on purpose so I'd go with the standard way

**Comment by lambdaR** [comment]
@asim have a look at schemToType method in dart_generator.go, is it smoother than the old one in go_generator.go? any thoughts ...

**Comment by asim** [comment]
Looks like a big improvement just in terms of readability. You should merge from upstream as there's conflicts in the PR

**Comment by lambdaR** [comment]
Dart generator is complete now.
I haven't changed schemToType in Go and Ts generator yet.
Working on Github workflow now.

**Comment by lambdaR** [comment]
To pave the way for the next contributor, we should add **HOWTO.md** file and _**TODO:**_ comments in the codebase that will act as landmarks to explain the steps you need to build a generator.

**Comment by asim** [comment]
Sounds like a good idea

**Comment by lambdaR** [comment]
@asim , I think we reached a point where you need to make a decision here. 

Restructuring and Dart generator is ready for review and merge (publishing dart clients not ready yet cause I need to make sure that Dart's steps in github/workflow produces the expected result before adding new step for publishing to pub.dev). 

**What we can do more to enhance client-gen:**

Currently, for Go and Dart we can easily combine the two in one generic generator, though the elephant in the room is Ts, it has traces everywhere but it can be refined to comply with others accordingly.

If so, we can turn client-gen back to a generic generator by passing it config files (yaml files) at runtime or put these config files in the root directory of micro/service repo, these files contains data specific to each language basically the variables at the beginning of schemaToType methods and other data too. 

Question is though, will the next language comply with the generic approach easily? or do we keep it freestyle like what I did ? 

Also, to speed up the time needed for running the action (before dart it's about 5+ minutes and with Dart it takes 8+ minutes), we need to run it in parallel i.e.  Each repo has its own dedicated version of generate.yml.

**Comment by asim** [comment]
OK I'll try review this on Monday. I think we just need to continue to iteratively evolve it as needed. I imagine trying to get each generator to comply to some generic interface is going to be hard unless that is just like `Compile(spec) ([]byte, error)` so it's fine to just let it go wherever its going. Looking at the way proto does it, you basically pass in a proto file and it outputs the generated code. It looks for generators based on flags like `--go_out` will attempt to find the binary `protoc-gen-go`. We can similarly do `m3o-gen-go` and related in future if we want.

**Comment by lambdaR** [comment]
The current code can generate Go, Ts, Dart Clients and their examples accordingly. 

We can test it without publishing packages/libraries if there's no issues we can then uncomment the parts responsible for publishing.

**Comment by asim** [comment]
Can you run this thing locally just to check if the generated code for JS and Go is unchanged

**Comment by lambdaR** [comment]
[result.txt](https://github.com/m3o/m3o/files/7974725/result.txt)

Here is the result of the `git diff old_gen..new_gen` command... from the first look it seems that the main diff is the ordering of attributes and file permission mode.

Note: i made a change in the Ts gen that replaces `{ [key: string]: any }` type with the actual type fetched from proto file directly see line **18960** and **18750** for example in the **_result.txt_** file above.

Will look again and see if there are any fatal diff …

**Comment by asim** [comment]
OK happy with that, will merge after cutting some releases for the previous versions just in case

**Pull request merged**
